# Generated by Django 4.1.2 on 2022-10-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('model_of_car', models.CharField(max_length=50, verbose_name='Модель автомобиля')),
                ('color_of_car', models.CharField(max_length=50, verbose_name='Цвет автомобиля')),
                ('state_number', models.CharField(max_length=9, verbose_name='Номер автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('password', models.BinaryField(verbose_name='Пароль')),
            ],
        ),
    ]
