# Generated by Django 4.0.3 on 2022-07-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('model_of_car', models.CharField(max_length=50, verbose_name='Модель автомобиля')),
                ('color_of_car', models.CharField(max_length=50, verbose_name='Цвет автомобиля')),
                ('state_number', models.CharField(max_length=9, verbose_name='Номер автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
            ],
        ),
    ]
