# Generated by Django 4.1.2 on 2022-10-14 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('model_of_car', models.CharField(max_length=50, verbose_name='Модель автомобиля')),
                ('color_of_car', models.CharField(max_length=50, verbose_name='Цвет автомобиля')),
                ('state_number', models.CharField(max_length=9, verbose_name='Номер автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('password', models.BinaryField(verbose_name='Пароль')),
                ('active_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
            ],
        ),
    ]
