# Generated by Django 4.0.3 on 2022-07-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('id_user', models.IntegerField(verbose_name='id заказчика')),
                ('id_taxist', models.IntegerField(verbose_name='id таксиста')),
                ('time', models.CharField(max_length=50, verbose_name='Время заказа')),
                ('address1', models.CharField(max_length=50, verbose_name='От куда')),
                ('address2', models.CharField(max_length=50, verbose_name='Куда')),
                ('ordered_time', models.CharField(max_length=50, verbose_name='Заказанное время')),
                ('tariff', models.CharField(max_length=50, verbose_name='Тариф')),
                ('payment', models.CharField(max_length=50, verbose_name='Оплата')),
                ('wishes', models.CharField(max_length=50, verbose_name='Пожелания')),
                ('distance', models.IntegerField(verbose_name='Расстояние, км')),
                ('cost', models.IntegerField(verbose_name='Стоимость, руб')),
            ],
        ),
    ]
