# Generated by Django 4.1.2 on 2022-10-14 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.IntegerField(verbose_name='id заказчика')),
                ('id_taxist', models.IntegerField(null=True, verbose_name='id таксиста')),
                ('time_of_order', models.CharField(max_length=50, verbose_name='Время заказа')),
                ('ordered_time', models.CharField(max_length=50, verbose_name='Заказанное время')),
                ('tariff', models.CharField(max_length=50, verbose_name='Тариф')),
                ('payment', models.CharField(max_length=50, verbose_name='Оплата')),
                ('wishes', models.CharField(max_length=50, verbose_name='Пожелания')),
                ('cost', models.FloatField(verbose_name='Стоимость, руб')),
                ('status', models.CharField(max_length=15, verbose_name='Статус')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='route.route')),
            ],
        ),
    ]
